# GitHub Build Pipeline
name: 'Build_Pipeline'

# Trigger on completion of GitHub_CI_Pipeline 
on:
  workflow_run:
    workflows: ['CI_Pipeline']
    types:
      - completed
    branches:
      - main
    paths:
      - src/**
      - dependencies/**
    tags:
      - '*'

# Permissions for private repo
permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  BuildLibrary:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
# Set-up Linux VM 
    runs-on: 'ubuntu-latest'

# Check out repo
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2 

# Install Python & upgrade pip
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.10' 

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

# Install dependencies
    - name: Install dependencies
      run: |
        pip install build
        pip install --upgrade setuptools 
        pip install -r dependencies/requirements.txt

# Build package
    - name: Build distribution
      run: |
        cd src/
        python -m build 
# --sdist --wheel --outdir dist/

# Publish artifacts
    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        tag: 'v0.2.2'
        allowUpdates: true
        replacesArtifacts: true