# Azure DevOps CI Pipeline

# This pipeline would trigger on changes to the main branch.
# Branch policies would also need to be added to lock the main branch from 
# direct commits and to run this pipeline - it differs slightly in syntax 
# from GitHub actions on the trigger.

# The pipeline will : 
### - set up a Linux VM & install Python 
### - Upgrade pip, install dependencies and testing libraries
### - Run tests on the src directory
### - Publish test results & code coverage report to Azure DevOps

trigger: 
  branches:
    include:
      - main
      
name: CI Pipeline
jobs:
- job: CI Pipeline Job
  
  pool: 
    vmImage: ubuntu-latest

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.9
      architecture: x64
    displayName: Set-up VM & Install Python

  - script: |
      python -m pip install --upgrade pip
      pip install pytest mock codecov pydocstyle pytest-cov pylint pylint_junit
    displayName: Install Test Dependencies
  
  - script: |
      pip install -r requirements.txt
    displayName: Install Codebase Dependencies

  - script: |
      pytest -v tests/ --doctest-modules --junitxml=unit-testresults.xml --cov=src/ --cov-append --cov-report=xml:coverage.xml --cov-report=html:htmlcov
    displayName: Run CI tests
  
  - script: |      
      pylint --output-format=pylint_junit.JUnitReporter --disable=C0114,C0115,C0116,E0110,E1101,E1123,R0801 src/my_custom_package/ > linting-testresults.xml
    displayName: Run PyLint Quality Tests
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-testresults.xml'
      testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)] - Python $(python.version) - Test Results'
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'
  
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'coverage.xml'
      reportDirectory: 'htmlcov'
    displayName: 'Publish Coverage Results'